name: Monthly Run
run-name: Github action triggered monthly generation of top resturant csv
on:
  schedule:
    - cron: "0 0 1 * *" # runs at midnight on the 1st of every month
  workflow_dispatch:
  pull_request:
jobs:
  Generate-Top-Restaurant-CSV:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: generate csv in root/out
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          GOOGLE_GEMINI_API_KEY: ${{ secrets.GOOGLE_GEMINI_API_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: |
          go build
          ./reddit-to-gmap generate-top-post-google-map-csv --subreddit foodnyc --num-posts 250 --use-cache
      - name: commit and push CSV file
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add out/*.csv
          git commit -m "Add generated restaurant CSV [skip ci]" || echo "No changes to commit"
          git push
